services:
  boldbi:
   container_name: boldbi
   image: syncfusion/boldbi
   restart: always
   ports:
     - 8085:80
   environment:
     # Required
     - BOLD_SERVICES_UNLOCK_KEY=<BOLD_SERVICES_UNLOCK_KEY>           # Set the unlock key value from the unlock_key.lic file, which can be obtained from the accounts page(https://www.boldbi.com/account).
     - BOLD_SERVICES_DB_TYPE=<data_base_server_type>                 # Set the database type.
     - BOLD_SERVICES_DB_HOST=<data_base_server_host>                 # Set the database server.
     - BOLD_SERVICES_DB_PORT=<data_base_server_port>                 # Set the database port number.
     - BOLD_SERVICES_POSTGRESQL_MAINTENANCE_DB=<maintenance_db_name> # Set the maintenance database for postgresql.
     - BOLD_SERVICES_DB_USER=<data_base_user_name>                   # Set the database username.
     - BOLD_SERVICES_DB_PASSWORD=<data_base_server_password>         # Set the database password.
     - BOLD_SERVICES_USER_EMAIL=<Bold_BI_user_email>                 # Set the site admin user Mail ID.
     - BOLD_SERVICES_USER_PASSWORD=<Bold_BI_user_password>           # Set the site admin user password.
   networks:
     - boldbi
   volumes:
     - boldbi_data:/application/app_data
   depends_on:
      pgdb:
        condition: service_healthy # Wait for pgdb to be healthy before starting boldbi
    
  pgdb:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Admin@123
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - boldbi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  boldbi:
  
volumes:
  boldbi_data:
  db_data:
